# Generated by Django 2.0 on 2017-12-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': '课程章节'},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='paper',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(through='web.TakeCourse', to='web.Course', verbose_name='学生参加的课程'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='point',
            field=models.CharField(default=0, max_length=50, verbose_name='教学特点'),
            preserve_default=False,
        ),
    ]
