# Generated by Django 2.0 on 2017-12-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='title',
            field=models.CharField(default='title', max_length=50, verbose_name='标题'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=models.TextField(max_length=500, verbose_name='课程详情'),
        ),
    ]
