# Generated by Django 2.0 on 2017-12-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20171218_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='belong_to',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=255, verbose_name='教师名'),
        ),
    ]
